### ISSUE TITLE
Continuous rising of GPU memory

### ISSUE THREAD

**Issue by glimmer-shining** [jokester-zzz/SSA-SC#2]
The way of updating training and validation loss results in the continuous rising of gpu memory

such as   loss[key]

it should be loss[key].item()

**Comment by jokester-zzz** [comment]
Hi!

Since many codes of this repo are inherited from LMSCNet, including this part of the code, I did not make detailed modifications. I checked the code and it seems that changing to loss[key].item() would be more elegant and reasonable. 

Thank you for your attention and correction.
