### ISSUE TITLE
The pretrained model can not be load by BEV_UNet

### ISSUE THREAD

**Issue by luzonghao1** [jokester-zzz/SSA-SC#3]
I am quite interested in your work and would like to implement it for my research. 

The pretrained model is BEV_3D_UNet, the BEV_UNet can not load it. Can you release the code？

**Comment by luzonghao1** [comment]
I have already solved it。 edit model.py file

#elif selected_model == 'SSA_SC':
elif selected_model == 'BEV_3D_UNet':

**Comment by jokester-zzz** [comment]
Congratulations! Since I changed my computer, I can't find other checkpoints for the ablation study. You can slightly modify the code and retrain the network. ^_^

**Comment by luzonghao1** [comment]
> Congratulations! Since I changed my computer, I can't find other checkpoints for the ablation study. You can slightly modify the code and retrain the network. ^_^

OK，thanks for your reply.
